"use client";
import {useState} from "react";
import type {Locale} from "@/data/content";
const entries:[string,string,string,string][] = [
 ["Go","Backend","adopt","Services with clear domain ownership"],["PostgreSQL","Data","adopt","Durable transactional state"],["Redis","Data","adopt","Caching and short-lived coordination"],["TypeScript","Web","adopt","Typed web development"],["React","Web","adopt","Reusable interfaces"],["Next.js","Web","adopt","Web application foundation"],["OpenAPI","Platform","adopt","Explicit API contracts"],
 ["Kafka","Data","use","Event transport when scale and operations justify it"],["OpenTelemetry","Operations","use","Portable telemetry instrumentation"],["OpenSearch","Data","use","Search workloads when needed"],["S3-compatible storage","Cloud","use","Object storage where suitable"],["Kubernetes","Cloud","use","Orchestration when complexity is justified"],
 ["AI-assisted engineering","AI","trial","Human-reviewed development workflows"],["Policy automation","Security","trial","Reviewable control automation"],["Platform abstractions","Platform","trial","Measured reuse across products"],
 ["Managed cloud services","Cloud","assess","Portability and operating cost assessment"],["Edge deployment","Cloud","assess","Placement and latency evaluation"],["International payment rails","Platform","assess","Future payment integration options"],["Developer tooling","Operations","assess","Emerging tools under evaluation"]
];
const rings=[{id:"adopt",en:"Adopt",fa:"استفاده تثبیت‌شده"},{id:"use",en:"Use When Justified",fa:"استفاده هدفمند"},{id:"trial",en:"Trial",fa:"آزمایش"},{id:"assess",en:"Assess",fa:"در حال ارزیابی"}];
export default function TechnologyRadar({locale}:{locale:Locale}) { const fa=locale==="fa"; const [category,setCategory]=useState("All");const [selected,setSelected]=useState<string|null>(null); const categories=["All",...new Set(entries.map(e=>e[1]))]; const visible=entries.filter(e=>category==="All"||e[1]===category); const current=entries.find(e=>e[0]===selected);
 return <section className="radarExperience shell" aria-label={fa?"رادار تعاملی فناوری":"Interactive technology radar"}><div className="radarFilters" role="group" aria-label={fa?"فیلتر حوزه":"Category filter"}>{categories.map(c=><button type="button" key={c} className={category===c?"selected":""} aria-pressed={category===c} onClick={()=>{setCategory(c);setSelected(null)}}>{c==="All"?(fa?"همه":"All"):c}</button>)}</div><div className="radarLayout"><div className="radarPlot" aria-label={fa?"چهار حلقه رادار":"Four radar rings"}>{rings.map((ring,ri)=><div className={`radarRing ring-${ring.id}`} key={ring.id}><span>{fa?ring.fa:ring.en}</span>{visible.filter(e=>e[2]===ring.id).map((e,i,arr)=>{const angle=(i/Math.max(arr.length,1))*Math.PI*2-(Math.PI/2)+ri*.3; const radius=ri===0?28:ri===1?33:ri===2?37:39;return <button type="button" key={e[0]} className={`radarBlip ${selected===e[0]?"active":""}`} style={{left:`${50+Math.cos(angle)*radius}%`,top:`${50+Math.sin(angle)*radius}%`}} onClick={()=>setSelected(e[0])} title={e[0]} aria-label={`${e[0]} — ${fa?ring.fa:ring.en}`}>{e[0].slice(0,2)}</button>})}</div>)}</div><div className="radarSide"><div className="radarDetail" aria-live="polite"><span>{current?.[1]|| (fa?"انتخاب فناوری":"SELECT A TECHNOLOGY")}</span><h2>{current?.[0]|| (fa?"فناوری‌ها را روی رادار بررسی کنید":"Explore the radar")}</h2><p>{current ? (fa ? ({adopt:"بخشی از پایه مهندسی فعلی است.",use:"در صورت نیاز روشن و توجیه عملیاتی به‌کار می‌رود.",trial:"در محدوده مشخص آزمایش می‌شود.",assess:"برای تصمیم‌های آینده ارزیابی می‌شود."} as Record<string,string>)[current[2]] : current[3]) : (fa?"هر نقطه را انتخاب کنید تا نقش آن در رویکرد مهندسی روشن شود.":"Select a point to see its role in the engineering approach.")}</p></div><div className="radarLegend">{rings.map(r=><div key={r.id}><i className={`legend-${r.id}`}/>{fa?r.fa:r.en}<b>{visible.filter(e=>e[2]===r.id).length.toLocaleString(fa?"fa-IR":"en-US")}</b></div>)}</div></div></div><div className="radarMobile">{rings.map(r=><section key={r.id}><h3>{fa?r.fa:r.en}</h3><div>{visible.filter(e=>e[2]===r.id).map(e=><button type="button" key={e[0]} onClick={()=>setSelected(e[0])}>{e[0]}</button>)}</div></section>)}</div></section>
}
